#!/usr/bin/env node
/**
 * Writes sitemap.xml from the HTML pages in the repo root.
 *
 * Generated rather than hand-kept so it cannot quietly go stale when a page is
 * added: it globs the root, and drops anything carrying a `noindex` robots meta
 * so the sitemap can never contradict the page itself.
 *
 * Deliberately <loc> only. Google ignores <changefreq> and <priority> outright,
 * and ignores <lastmod> unless it is consistently accurate — which a value
 * written once and never regenerated is not. Emitting them would imply a
 * precision this file does not have.
 *
 * Usage: node scripts/build-sitemap.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://prismmtg.com';

// Pages that resolve but are not worth indexing. Both keep their share tags, so
// a pasted link still previews; they are just not offered to a crawler.
//
//   profile.html  an account screen. Logged out it is a sign-in stub with
//                 nothing to rank.
//   links.html    the QR and social funnel page (#243). It is reached by scan
//                 or from a bio, never by search, and a thin hub of outbound
//                 links in the sitemap mostly competes with the homepage for
//                 the same queries. Named here ahead of the file landing, so
//                 the sitemap cannot pick it up the moment #245 merges.
const EXCLUDE = new Set(['profile.html', 'links.html']);

// Ordered most to least important. Anything found on disk but not listed here
// is appended, so a new page still lands in the sitemap without editing this.
const ORDER = ['index.html', 'build.html', 'guide.html', 'tools.html', 'gallery.html', 'privacy.html', 'terms.html'];

const pages = readdirSync(ROOT)
  .filter(f => f.endsWith('.html'))
  .filter(f => !EXCLUDE.has(f))
  .filter(f => !/<meta\s+name=["']robots["'][^>]*noindex/i.test(readFileSync(join(ROOT, f), 'utf8')))
  .sort((a, b) => {
    const ia = ORDER.indexOf(a), ib = ORDER.indexOf(b);
    return (ia === -1 ? ORDER.length : ia) - (ib === -1 ? ORDER.length : ib) || a.localeCompare(b);
  });

// index.html is served at the root, and its canonical says so.
const loc = f => `${SITE}/${f === 'index.html' ? '' : f}`;

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(f => `  <url><loc>${loc(f)}</loc></url>`).join('\n')}
</urlset>
`;

writeFileSync(join(ROOT, 'sitemap.xml'), xml);
console.log(`Wrote sitemap.xml (${pages.length} URLs)`);
for (const f of pages) console.log(`  ${loc(f)}`);
