#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Puts the Stripe business account's live keys into Netlify's Production
# context and proves the webhook is reachable (#253). Nothing is captured or
# written locally: every value goes straight from the Stripe/Supabase tab
# into the Netlify tab, so no secret passes through this terminal. Re-run it
# to rotate a key; skip stages you don't need with Enter.

WEBHOOK_URL="https://prismmtg.com/api/stripe-webhook"
SUPABASE_REF="clqxysoimlsjfmnjbxsa"
TOTAL_STAGES=10

# netlify_add KEY SECRET? — the one Netlify dialog every value goes through.
netlify_add() {
  local key="$1" secret="$2"
  say ""
  say "${BOLD}In the Netlify tab, add ${key}:${RESET}"
  step "Add a variable → Add a single variable (or ⋯ → Edit if ${key} already exists)."
  step "Key: ${BOLD}${key}${RESET}"
  if [[ "$secret" == "secret" ]]; then
    step "Tick ${BOLD}Contains secret values${RESET}."
  fi
  step "Scopes: All scopes. If that's greyed out, Specific scopes → tick Functions and Runtime."
  step "Values: ${BOLD}Different value for each deploy context${RESET} → paste into ${BOLD}Production${RESET} only."
  note "Leave Deploy Previews / Branch deploys empty: previews must never hold live keys."
  step "Create variable (or Save)."
  pause "Press Enter once ${key} is saved in Netlify."
}

banner "PRISM · Stripe business account → Netlify (#253)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Netlify — look at what's there now"
say "Production's webhook answers 500 \"Not configured\": at least one of four"
say "variables is missing from the context/scope edge functions read."
open_url "https://app.netlify.com/"
step "Open the PRISM project (prismmtg.com) → Project configuration → Environment variables."
step "Keep this tab open: every later stage ends by pasting a value here."
say ""
say "For each variable below, note whether it exists, its scopes, and whether it"
say "has a ${BOLD}Production${RESET} value (not just Deploy Previews):"
note "  STRIPE_SECRET_KEY  STRIPE_WEBHOOK_SECRET  STRIPE_PRICE_ID  STRIPE_ANNUAL_PRICE_ID"
note "  STRIPE_PORTAL_CONFIGURATION_ID (optional)  SUPABASE_URL  SUPABASE_SERVICE_ROLE_KEY"
say ""
warn "Any existing STRIPE_* value is from the personal/sandbox account. The next"
warn "stages replace all of them, so edit rather than add a duplicate."
note "A var scoped only to Builds is invisible to edge functions: that alone gives a 500."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Stripe — business account, live mode"
open_url "https://dashboard.stripe.com/dashboard"
step "Top-left account switcher: pick the ${BOLD}business${RESET} account, not the personal one."
step "Make sure you are NOT in a sandbox or test mode (no orange banner across the top)."
say ""
say "If the dashboard is asking you to finish activation (the bank letter), stop"
say "here: live keys don't work until Stripe confirms. Re-run this wizard afterwards."
if ! confirm "Business account, live mode, activated?"; then
  warn "Stopping. Nothing in Netlify has changed."
  exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Stripe — Membership prices"
open_url "https://dashboard.stripe.com/products?active=true"
say "Membership is \$3/mo or \$30/yr USD (PRODUCT.md). You need both price IDs."
step "If there's no Membership product yet: + Create product → name ${BOLD}PRISM Membership${RESET}."
step "   Price 1: Recurring, \$3.00 USD, Monthly.  Price 2 (More pricing options): Recurring, \$30.00 USD, Yearly."
step "Open the product. In the Pricing list, open the ${BOLD}monthly${RESET} price → copy its ID (price_…)."
netlify_add STRIPE_PRICE_ID plain
step "Back in Stripe, open the ${BOLD}yearly${RESET} price → copy its ID (price_…)."
note "Optional. The site only offers monthly today; this readies the yearly checkout path."
netlify_add STRIPE_ANNUAL_PRICE_ID plain

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Stripe — secret key"
open_url "https://dashboard.stripe.com/apikeys"
step "Standard keys → Secret key → Reveal (or Create secret key) → copy it."
warn "It must start ${BOLD}sk_live_${RESET}. sk_test_ means you're still in test mode or a sandbox."
netlify_add STRIPE_SECRET_KEY secret

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Stripe — customer portal"
say "Manage Billing opens this portal. In live mode it fails until it has been"
say "saved once, and the settings don't carry over from the sandbox."
open_url "https://dashboard.stripe.com/settings/billing/portal"
step "Customers can cancel subscriptions: ${BOLD}on${RESET}, mode ${BOLD}At the end of the billing period${RESET}."
step "Cancellation reasons / retention coupons: ${BOLD}off${RESET} (runbook, #218 save offer decision)."
step "Customers can update payment methods: ${BOLD}on${RESET}."
step "Save changes."
say ""
say "Using the default configuration: leave STRIPE_PORTAL_CONFIGURATION_ID unset."
say "If Netlify already has one from the sandbox (bpc_…), ${BOLD}delete it${RESET}: a sandbox"
say "configuration ID doesn't exist in the business account and every portal open fails."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Stripe — webhook destination"
open_url "https://dashboard.stripe.com/webhooks"
step "+ Add destination → Events from: ${BOLD}Your account${RESET}. Keep the default API version."
step "Select these four events, nothing else:"
note "    checkout.session.completed"
note "    customer.subscription.updated"
note "    customer.subscription.deleted"
note "    invoice.payment_failed"
step "Payload style, if asked: ${BOLD}Snapshot${RESET} (the handler reads event.data.object)."
step "Destination type: Webhook endpoint → URL: ${BOLD}${WEBHOOK_URL}${RESET} → Create destination."
step "On the new destination: Signing secret → Reveal → copy it (whsec_…)."
warn "The secret belongs to this destination in this account. The sandbox one won't verify."
netlify_add STRIPE_WEBHOOK_SECRET secret

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Stripe — retire the sandbox endpoint"
say "The personal/sandbox account still has \"SandboxPRISM\" pointing at production."
say "Once Netlify holds the business secret, every sandbox delivery fails signature"
say "checks and Stripe keeps retrying it and sending failure emails."
step "Account switcher → the personal/sandbox account → Workbench → Webhooks."
step "Open SandboxPRISM → ⋯ → ${BOLD}Disable${RESET} (or Delete)."
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Supabase — URL and service key"
open_url "https://supabase.com/dashboard/project/${SUPABASE_REF}/settings/api-keys"
say "SUPABASE_URL is not secret:"
note "    https://${SUPABASE_REF}.supabase.co"
netlify_add SUPABASE_URL plain
say "For SUPABASE_SERVICE_ROLE_KEY:"
step "Legacy API Keys tab → service_role → Reveal → copy (eyJ…)."
note "The functions send this key as a Bearer token too, which the JWT-shaped legacy"
note "key is known to handle. A newer sb_secret_ key may work; stage 10 would tell."
warn "This key bypasses RLS. It goes in Netlify and nowhere else."
netlify_add SUPABASE_SERVICE_ROLE_KEY secret

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Netlify — redeploy and probe"
say "Edge functions only see new variables after a new deploy."
step "Netlify → Deploys → Trigger deploy → ${BOLD}Deploy project${RESET} (git push to main also works)."
pause "Press Enter once the deploy shows Published."
say ""
say "Probing ${WEBHOOK_URL} with an unsigned POST."
note "400 \"Invalid signature\" = all four vars present (the good answer)."
note "500 \"Not configured\" = still missing; the function log names which one."
while true; do
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$WEBHOOK_URL" -d '{}' || echo "000")
  if [[ "$code" == "400" ]]; then
    printf '  %s✓ webhook answered 400: configured%s\n' "$GREEN" "$RESET"
    break
  fi
  warn "webhook answered ${code}, expected 400."
  step "Netlify → Logs → Edge Functions → look for \"missing env vars: …\"."
  note "Usual causes: value only on Deploy Previews, Builds-only scope, no redeploy yet."
  confirm "Fixed it and redeployed? Probe again" || break
done
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Live round trip (real \$3 charge, refunded)"
say "The probe only proves the vars exist. The issue asks for a real"
say "Checkout → webhook → Supabase trip before launch. It costs one real \$3"
say "charge, which you refund in the same sitting."
if confirm "Run the round trip now?"; then
  open_url "https://prismmtg.com/profile.html"
  say "With enforcement off every signed-in account is entitled, so the site never"
  say "shows a Join button. Start checkout from the console instead."
  step "Sign up a ${BOLD}throwaway account${RESET} (a +alias of your email) and sign in, so the"
  note "  test Stripe customer and subscription never attach to your real account."
  step "DevTools console on prismmtg.com:"
  note "    (await import('/js/modules/billing.js')).startCheckout()"
  step "Pay \$3 with a real card → Stripe returns you to the profile."
  step "Stripe → Workbench → Webhooks → the new destination: deliveries show ${BOLD}200${RESET}."
  step "Supabase SQL editor (open below), run:"
  note "    SELECT status, price_id, current_period_end, updated_at FROM subscriptions"
  note "    WHERE user_id = (SELECT id FROM auth.users WHERE email = '<throwaway email>');"
  step "Expect status 'active' and the monthly price_… from stage 3."
  open_url "https://supabase.com/dashboard/project/${SUPABASE_REF}/sql/new"
  pause "Press Enter once the row reads active."
  step "Console again, to open the portal (the profile hides it while enforcement is off):"
  note "    (await import('/js/modules/billing.js')).openBillingPortal()"
  step "Cancel the Membership. Re-run the query: cancel_at_period_end = true."
  step "Stripe → Payments → the \$3 charge → Refund."
  note "Full portal checklist: docs/runbooks/enforcement-cutover.md → Portal configuration and rehearsal."
  pause
else
  note "Skipped. Do this before the PR #236 changeover. It's in the runbook's Stripe environment section."
fi

finish
say "Stripe (business, live) → Netlify Production is wired. Close #253 once the"
say "round trip has passed."
printf '\n'
