#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Human-only setup for the commission relay (#182 → Sending / Sending domain):
# a Resend domain for relay.prismmtg.com, an explicit DMARC sp=, a
# sending-only Resend key, a Turnstile widget, and the two secrets in
# Netlify's Production context. Like setup-stripe-netlify.sh, nothing is
# written locally: secrets go straight from the vendor tab into the Netlify
# tab. The one secret typed here (the optional test send) stays in memory.

DOMAIN="relay.prismmtg.com"
FROM="commissions@${DOMAIN}"
TOTAL_STAGES=8

# dns NAME TYPE — print answers, one per line. dig if present, else Cloudflare
# DNS-over-HTTPS (dig isn't installed everywhere).
dns() {
  if command -v dig >/dev/null 2>&1; then
    dig +short "$1" "$2"
  else
    curl -s -H 'accept: application/dns-json' \
      "https://cloudflare-dns.com/dns-query?name=$1&type=$2" \
      | grep -o '"data":"[^}]*' | sed 's/^"data":"//; s/"$//; s/\\"/"/g'
  fi
}

# check_dns NAME TYPE NEEDLE — ✓/✗ on whether NAME's TYPE answer contains NEEDLE.
check_dns() {
  local out; out=$(dns "$1" "$2" || true)
  if [[ "$out" == *"$3"* ]]; then
    printf '  %s✓%s %s %s\n' "$GREEN" "$RESET" "$2" "$1"; return 0
  fi
  printf '  %s✗%s %s %s %s(got: %s)%s\n' "$RED" "$RESET" "$2" "$1" "$DIM" "${out:-nothing}" "$RESET"
  return 1
}

# netlify_add KEY — same Netlify dialog as setup-stripe-netlify.sh.
netlify_add() {
  local key="$1"
  say ""
  say "${BOLD}In the Netlify tab, add ${key}:${RESET}"
  step "Add a variable → Add a single variable (or ⋯ → Edit if ${key} already exists)."
  step "Key: ${BOLD}${key}${RESET}"
  step "Tick ${BOLD}Contains secret values${RESET}."
  step "Scopes: All scopes. If that's greyed out, Specific scopes → tick Functions and Runtime."
  step "Values: ${BOLD}Different value for each deploy context${RESET} → paste into ${BOLD}Production${RESET} only."
  note "Leave Deploy Previews / Branch deploys empty: previews must never send real mail."
  step "Create variable (or Save)."
  pause "Press Enter once ${key} is saved in Netlify."
}

banner "PRISM · Commission relay: Resend + Turnstile → Netlify (#182)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Resend — is there room for another domain?"
say "The relay must live on its own subdomain, ${BOLD}${DOMAIN}${RESET}, apart from"
say "send.prismmtg.com (account email). Resend's free tier allows ${BOLD}one${RESET} domain,"
say "and the account (defcat's) may already be spending it."
if [[ -n "$(dns "resend._domainkey.${DOMAIN}" TXT || true)" ]]; then
  note "Public DNS already has a Resend DKIM record for ${DOMAIN}: it may already be"
  note "added in Resend. If it's listed there, the allowance is already spent on it: answer y."
fi
open_url "https://resend.com/domains"
step "Sign in to the Resend account defcat uses. Count the domains listed."
open_url "https://resend.com/settings/billing"
step "Check the plan and its domain allowance."
say ""
if ! confirm "Does the plan allow adding ${DOMAIN} without going over?"; then
  warn "Stopping. Upgrading (or a separate Resend account) is a deliberate"
  warn "decision: price it and record it on #182."
  warn "Do NOT put the relay on send.prismmtg.com instead: it would share account"
  warn "email's sending reputation with strangers' messages."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Resend — add ${DOMAIN}"
open_url "https://resend.com/domains"
note "Already listed? Skip to the next stage."
step "+ Add domain → Name: ${BOLD}${DOMAIN}${RESET}"
step "Region: ${BOLD}us-east-1${RESET} (send.prismmtg.com uses it too; matching is simplest)."
step "Add. Resend now shows a DNS records table (DKIM, SPF MX + TXT, maybe DMARC)."
note "Keep this tab open: the next stage copies each row into Netlify DNS."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Netlify DNS — add the records, then verify"
say "prismmtg.com's nameservers are NS1 (dns*.p01.nsone.net), which is Netlify DNS."
open_url "https://app.netlify.com/teams/"
step "Netlify → Domains → prismmtg.com → DNS settings → Add new record, once per row:"
note "    TXT  resend._domainkey.relay   (DKIM, long p=… value)"
note "    MX   send.relay   feedback-smtp.us-east-1.amazonses.com   priority 10"
note "    TXT  send.relay   v=spf1 include:amazonses.com ~all"
note "Names are relative to prismmtg.com. Copy the exact names and values Resend shows;"
note "the list above is the usual shape, not the source of truth."
warn "Don't add the DMARC row Resend suggests: DMARC lives on the root domain (stage 4)."
pause "Press Enter once the records are saved."
while true; do
  say ""
  say "Checking public DNS…"
  ok=0
  check_dns "resend._domainkey.${DOMAIN}" TXT "p=" || ok=1
  check_dns "send.${DOMAIN}" MX "amazonses.com" || ok=1
  check_dns "send.${DOMAIN}" TXT "v=spf1" || ok=1
  if (( ok == 0 )); then
    say ""
    step "Resend → ${DOMAIN} → ${BOLD}Verify DNS Records${RESET}. Wait for the status to read Verified."
    pause "Press Enter once Resend shows Verified."
    break
  fi
  note "New records can take a few minutes to show up. If Resend used other names, check those."
  confirm "Check again?" || { SKIPPED+=("DNS records for ${DOMAIN} weren't visible yet; verify in Resend"); break; }
done

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "DMARC — set sp= on the root domain"
say "A root DMARC policy governs every subdomain unless sp= says otherwise, so"
say "both send. and relay. inherit it. Make that explicit."
say ""
say "Current _dmarc.prismmtg.com:"
current=$(dns _dmarc.prismmtg.com TXT || true)
note "    ${current:-<no record>}"
if [[ "$current" == *"sp="* ]]; then
  printf '  %s✓%s sp= is already set explicitly.\n' "$GREEN" "$RESET"
  pause
else
  warn "No sp= tag: subdomains inherit p= by accident."
  say "Pick a subdomain policy. While both senders are new, matching the root is safe:"
  note "    v=DMARC1; p=none; sp=none;"
  note "Tighten later (sp=quarantine) once Resend shows both subdomains passing."
  open_url "https://app.netlify.com/teams/"
  step "Netlify → Domains → prismmtg.com → DNS settings → the TXT ${BOLD}_dmarc${RESET} record → Edit."
  step "Keep the existing tags, add ${BOLD}sp=<your choice>;${RESET} → Save."
  pause "Press Enter once saved."
  while ! check_dns _dmarc.prismmtg.com TXT "sp="; do
    confirm "Not visible yet. Check again?" || { SKIPPED+=("_dmarc.prismmtg.com still has no sp="); break; }
  done
  pause
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Resend — sending-only API key"
open_url "https://resend.com/api-keys"
step "Create API key → Name: ${BOLD}prism-commission-relay${RESET}"
step "Permission: ${BOLD}Sending access${RESET} → Domain: ${BOLD}${DOMAIN}${RESET} (not All domains)."
step "Add → copy the key (re_…). Resend shows it once."
open_url "https://app.netlify.com/teams/"
step "Netlify → the PRISM project (prismmtg.com) → Project configuration → Environment variables."
netlify_add RESEND_API_KEY

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Resend — prove the key and domain with one test email"
say "A sending-only key can't read domain status, so the probe is a real send:"
say "Resend refuses it unless the key is valid and ${DOMAIN} is verified."
if confirm "Send one test email from ${FROM}?"; then
  ask TEST_TO "Send it to (your address):"
  ask_secret PROBE_KEY "Paste the same re_… key (kept in memory only):"
  resp=$(curl -s -w '\n%{http_code}' https://api.resend.com/emails \
    -H "Authorization: Bearer ${PROBE_KEY}" -H 'Content-Type: application/json' \
    -d "{\"from\":\"PRISM commissions <${FROM}>\",\"to\":[\"${TEST_TO}\"],\"subject\":\"PRISM relay test\",\"text\":\"relay.prismmtg.com can send.\"}" \
    || printf '\n000')
  PROBE_KEY=""
  code=${resp##*$'\n'}
  if [[ "$code" == "200" ]]; then
    printf '  %s✓ Resend accepted it (200).%s Check the inbox, and in the message source\n' "$GREEN" "$RESET"
    note "  look for spf=pass, dkim=pass, dmarc=pass."
  else
    warn "Resend answered ${code}: ${resp%$'\n'*}"
    note "401/403 = wrong key or domain not verified yet. Recheck stages 3 and 5."
    SKIPPED+=("Resend test send failed (${code})")
  fi
else
  SKIPPED+=("Resend test send from ${FROM}")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — Turnstile widget"
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Sign in (a free Cloudflare account is enough; the domain doesn't need to be on Cloudflare)."
step "Add widget → Name: ${BOLD}PRISM commissions${RESET}"
step "Hostnames: ${BOLD}prismmtg.com${RESET} and ${BOLD}localhost${RESET} (for the dev server on :3456)."
step "Widget mode: ${BOLD}Managed${RESET}. Pre-clearance: No. → Create."
say ""
say "The site key is public: it goes in client code later."
ask TURNSTILE_SITE_KEY "Paste the Site Key (0x…):"
say ""
say "The secret key goes to Netlify only."
step "Copy the ${BOLD}Secret Key${RESET}."
netlify_add TURNSTILE_SECRET_KEY

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Netlify — check both are in Production"
step "Environment variables list: RESEND_API_KEY and TURNSTILE_SECRET_KEY each show a"
step "${BOLD}Production${RESET} value and include the Functions scope."
note "/api/commission-edge doesn't exist yet, so there's nothing to probe. Edge functions"
note "read new variables only after a deploy; the deploy that ships the function covers it."
pause

finish
say "Commission relay sending is set up on ${BOLD}${DOMAIN}${RESET}."
say ""
say "${BOLD}Turnstile SITE key${RESET} (public; pass it on for the commission form):"
printf '\n    %s%s%s\n\n' "$BOLD" "${TURNSTILE_SITE_KEY:-<not captured>}" "$RESET"
